<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>

    <RootNamespace>ValidSphere</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Version>0.1.0-preview.1</Version>
    <Title>ValidSphere - Runtime Guards and Invariants for .NET</Title>
    <Authors>0siris</Authors>
    <Description>A lightweight, extensible assertion and guard library for modern .NET.</Description>
    <PackageTags>guard;guard-clauses;assertions;invariants;runtime-validation;preconditions;nullability;dotnet</PackageTags>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageReadmeFile>Readme.md</PackageReadmeFile>
    <PackageProjectUrl>https://github.com/0siris/ValidSphere</PackageProjectUrl>
    <RepositoryUrl>https://github.com/0siris/ValidSphere</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
  </PropertyGroup>

  <ItemGroup>
    <None Include="Readme.md" Pack="true" PackagePath="\" />
  </ItemGroup>

</Project>
